Change structure to match CNB

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,4 +1,19 @@
 #!/usr/bin/env bash
-# bin/detect <build-dir>
-echo 'nginx-buildpack'
-exit 0
+
+# fail hard
+set -o pipefail
+
+bp_dir="$(
+    cd "$(dirname "$0")/.."
+    pwd
+)" # absolute path
+target_dir="${bp_dir}/target"
+
+"${target_dir}/bin/detect" "$(pwd)" >/dev/null 2>&1
+
+EXITCODE=$?
+
+case $EXITCODE in
+1) exit 100 ;;
+*) exit $EXITCODE ;;
+esac
